# **Preparing Input Data for Chemprop Modeling**

This notebook extracts the SMILES strings (canonical_smiles) and corresponding pIC50 activity values from the cleaned training and test datasets. These are saved as CSV files with the required Chemprop format (smiles, pIC50) for model training and evaluation.

In addition, the notebook extracts the RFECV-selected descriptor features from the datasets by removing metadata columns. These reduced feature matrices are saved separately so they can be used as external molecular features during Chemprop training.

The resulting files provide both:

- Standard Chemprop input datasets (SMILES + target values)

- Additional descriptor feature matrices for use with Chemprop’s feature-based modeling options.

In [ ]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

Mounted at /content/drive

In [ ]:
#!pip install chemprop

In [ ]:
# === Paths to datasets ===

reu_path = "/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/data/descriptors/reduced_features_reu_2"
meta_cols = ['molecule_chembl_id', 'canonical_smiles', 'activity_class', 'pIC50']

In [ ]:
targets = ["5-HT6","ache", "bace1", "buche","esr1","gsk-3beta", "mao-b"]

target=targets[6]

In [ ]:
import pandas as pd

df_train = pd.read_csv(f"{reu_path}/{target}_train_reu.csv").dropna(how="any")
df_test = pd.read_csv(f"{reu_path}/{target}_test_reu.csv").dropna(how="any")

In [ ]:
df_train.head()

,molecule_chembl_id,canonical_smiles,activity_class,pIC50,rdk_MaxAbsEStateIndex,rdk_MinAbsEStateIndex,rdk_MinEStateIndex,rdk_qed,rdk_SPS,rdk_MolWt,...,fp_2009,fp_2015,fp_2017,fp_2018,fp_2021,fp_2025,fp_2033,fp_2041,fp_2042,fp_2044
0,CHEMBL4870887,Cc1ccc(NC(=O)c2csc3ccccc3c2=O)cc1C,active,8.474955,12.427001,0.182341,-0.365504,0.773368,10.636364,309.390,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL495714,COc1ccc(-c2csc(NN=C3CCCC(C)C3)n2)cc1,inactive,5.345823,5.176717,0.750421,0.750421,0.824606,20.090909,315.442,...,0,0,0,0,0,1,0,0,0,0
2,CHEMBL972,C#CCN(C)C(C)Cc1ccccc1,active,8.167491,5.268946,0.493935,0.493935,0.653025,12.428571,187.286,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL564763,COc1ccc(C2=NN(C(C)=O)CC2)cc1OC,inactive,4.055517,11.220592,0.036596,-0.036596,0.817055,14.388889,248.282,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL4575664,O=C(C=Cc1ccc(OCCN2CCCCC2)cc1)c1ccc(OCCN2CCCCC2...,inactive,4.764472,12.605641,0.062430,-0.246088,0.361569,17.485714,478.633,...,0,0,0,0,0,0,1,0,0,0

In [ ]:


# Combine SMILES and pIC50 for training
train_df = pd.DataFrame({
    "smiles": df_train["canonical_smiles"],
    "pIC50": df_train["pIC50"]
})

# Combine SMILES and pIC50 for testing
test_df = pd.DataFrame({
    "smiles": df_test["canonical_smiles"],
    "pIC50": df_test["pIC50"]
})

# Save to CSV in Chemprop-compatible format
train_df.to_csv(f"/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/chemprop/input_data/{target}_train.csv", index=False)
test_df.to_csv(f"/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/chemprop/input_data/{target}_test.csv", index=False)

print("Saved 'train.csv' and 'test.csv' for Chemprop.")

Saved 'train.csv' and 'test.csv' for Chemprop.

In [ ]:
train_df.head()

                                              smiles     pIC50
0                 Cc1ccc(NC(=O)c2csc3ccccc3c2=O)cc1C  8.474955
1               COc1ccc(-c2csc(NN=C3CCCC(C)C3)n2)cc1  5.345823
2                              C#CCN(C)C(C)Cc1ccccc1  8.167491
3                     COc1ccc(C2=NN(C(C)=O)CC2)cc1OC  4.055517
4  O=C(C=Cc1ccc(OCCN2CCCCC2)cc1)c1ccc(OCCN2CCCCC2...  4.764472

In [ ]:
test_df.head()

                                              smiles     pIC50
0  CC(C)(C)c1cc(C=CC(=O)NCCC2CCN(Cc3ccccc3)CC2)cc...  5.070581
1  COc1ccccc1CN(C)CCCCCCOc1cc(O)c2c(=O)c3ccccc3sc2c1  6.420216
2                      O=c1c(C=Cc2ccccc2)coc2ccccc12  7.568636
3                 C#CCN(C)C(C)Cc1ccc(NCc2ncccc2C)cc1  6.283997
4               CCCCC(CC)=NNc1nc(-c2ccc3ccccc3c2)cs1  5.424812

In [ ]:
# Extract RFECV features from train and test sets
X_train_reu = df_train.drop(columns=meta_cols)
X_test_reu = df_test.drop(columns=meta_cols)

# Save to CSV
X_train_reu.to_csv(f"/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/chemprop/input_data/reu_features/{target}_train_reu.csv", index=False)
X_test_reu.to_csv(f"/content/drive/MyDrive/Colab Notebooks/ESOFT-MSC/thesis-project/chemprop/input_data/reu_features/{target}_test_reu.csv", index=False)

In [ ]:
X_train_reu.head()

,rdk_MaxAbsEStateIndex,rdk_MinAbsEStateIndex,rdk_MinEStateIndex,rdk_qed,rdk_SPS,rdk_MolWt,rdk_FpDensityMorgan1,rdk_FpDensityMorgan2,rdk_FpDensityMorgan3,rdk_BCUT2D_MWHI,...,fp_2009,fp_2015,fp_2017,fp_2018,fp_2021,fp_2025,fp_2033,fp_2041,fp_2042,fp_2044
0,12.427001,0.182341,-0.365504,0.773368,10.636364,309.390,1.045455,1.818182,2.590909,32.133442,...,0,0,0,0,0,0,0,0,0,0
1,5.176717,0.750421,0.750421,0.824606,20.090909,315.442,1.318182,2.136364,2.863636,32.133491,...,0,0,0,0,0,1,0,0,0,0
2,5.268946,0.493935,0.493935,0.653025,12.428571,187.286,1.357143,2.000000,2.571429,15.109687,...,0,0,0,0,0,0,0,0,0,0
3,11.220592,0.036596,-0.036596,0.817055,14.388889,248.282,1.277778,2.000000,2.555556,16.507790,...,0,0,0,0,0,0,0,0,0,0
4,12.605641,0.062430,-0.246088,0.361569,17.485714,478.633,0.771429,1.314286,1.885714,16.480604,...,0,0,0,0,0,0,1,0,0,0